spring:
  profiles:
    active: dev
  jpa:
    hibernate:
#      ddl-auto: create-drop
    #自动生成数据表
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
    #以时间戳的方式返回给前端
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

#    active: prod


# 指定api 是所有controller的根包
missyou:
  api-package: com.o0u0o.missyou.api
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L,M,N

# 微信相关配置
wx:
  appid: wxd86e4c273a50faa8
  appsecret: 808ea4c46faa5eac8ea29ad67e6d0407
#  绿洲保
#  appid: wxe20af5f02e9e0de6
#  appsecret: LZZHOUBAO2020jkjdhfiuie90quwu329
  code2session-url: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code

